import type {
  Patient,
  Appointment,
  AiSummary,
  ChatMessage,
  Conversation,
  DoctorNote,
  AppNotification,
  DoctorProfile,
} from './types';

// All dates are anchored relative to "today" so the dashboard always looks live.
const today = new Date();
const iso = (d: Date) => d.toISOString().slice(0, 10);
const addDays = (d: Date, n: number) => {
  const r = new Date(d);
  r.setDate(r.getDate() + n);
  return r;
};
const isoDT = (d: Date) => d.toISOString();
const at = (day: Date, h: number, m = 0) => {
  const r = new Date(day);
  r.setHours(h, m, 0, 0);
  return r;
};

export const doctor: DoctorProfile = {
  id: 'doc-1',
  name: 'Dr. Sarah Chen',
  title: 'MD, FACC',
  specialty: 'Cardiology',
  avatarUrl:
    'https://images.pexels.com/photos/5407206/pexels-photo-5407206.jpeg?auto=compress&cs=tinysrgb&w=256',
  email: 'sarah.chen@clinicos.health',
  phone: '+1 (415) 555-0142',
  license: 'CA-MD-99421',
  hospital: 'Bayview Medical Center',
  yearsExperience: 12,
};

export const patients: Patient[] = [
  {
    id: 'p-1',
    name: 'James Morrison',
    age: 58,
    gender: 'Male',
    phone: '+1 (415) 555-0181',
    email: 'james.morrison@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'A+',
    status: 'critical',
    lastVisit: iso(addDays(today, -3)),
    address: '284 Oak Street, San Francisco, CA 94102',
    emergencyContact: {
      name: 'Linda Morrison',
      relationship: 'Spouse',
      phone: '+1 (415) 555-0182',
    },
    medicalHistory: [
      {
        id: 'mh-1',
        date: iso(addDays(today, -90)),
        title: 'Myocardial Infarction',
        description:
          'Acute STEMI treated with primary PCI. Stent placed in LAD.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
      {
        id: 'mh-2',
        date: iso(addDays(today, -180)),
        title: 'Hypertension Diagnosis',
        description: 'Stage 2 hypertension, started on ACE inhibitor.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
      {
        id: 'mh-3',
        date: iso(addDays(today, -365)),
        title: 'Type 2 Diabetes',
        description: 'HbA1c 7.8%, started on metformin.',
        doctor: 'Dr. Alan Park',
        department: 'General Medicine',
      },
    ],
    medications: [
      {
        id: 'med-1',
        name: 'Metoprolol',
        dosage: '50mg',
        frequency: 'Twice daily',
        startDate: iso(addDays(today, -90)),
        status: 'active',
      },
      {
        id: 'med-2',
        name: 'Atorvastatin',
        dosage: '40mg',
        frequency: 'Once daily at bedtime',
        startDate: iso(addDays(today, -90)),
        status: 'active',
      },
      {
        id: 'med-3',
        name: 'Lisinopril',
        dosage: '10mg',
        frequency: 'Once daily',
        startDate: iso(addDays(today, -180)),
        status: 'active',
      },
      {
        id: 'med-4',
        name: 'Metformin',
        dosage: '500mg',
        frequency: 'Twice daily with meals',
        startDate: iso(addDays(today, -365)),
        status: 'active',
      },
    ],
    allergies: ['Penicillin', 'Shellfish'],
    conditions: ['Coronary Artery Disease', 'Hypertension', 'Type 2 Diabetes'],
  },
  {
    id: 'p-2',
    name: 'Emily Rodriguez',
    age: 34,
    gender: 'Female',
    phone: '+1 (415) 555-0193',
    email: 'emily.r@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'O-',
    status: 'follow-up',
    lastVisit: iso(addDays(today, -14)),
    address: '512 Pine Avenue, San Francisco, CA 94110',
    emergencyContact: {
      name: 'Carlos Rodriguez',
      relationship: 'Brother',
      phone: '+1 (415) 555-0194',
    },
    medicalHistory: [
      {
        id: 'mh-4',
        date: iso(addDays(today, -14)),
        title: 'Palpitations Evaluation',
        description: 'Episodic palpitations, Holter monitor ordered.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
      {
        id: 'mh-5',
        date: iso(addDays(today, -400)),
        title: 'Migraine with Aura',
        description: 'Chronic migraine managed with lifestyle changes.',
        doctor: 'Dr. Nina Patel',
        department: 'Neurology',
      },
    ],
    medications: [
      {
        id: 'med-5',
        name: 'Sumatriptan',
        dosage: '50mg',
        frequency: 'As needed for migraine',
        startDate: iso(addDays(today, -400)),
        status: 'active',
      },
    ],
    allergies: ['Latex'],
    conditions: ['Migraine', 'Anxiety'],
  },
  {
    id: 'p-3',
    name: 'Robert Kim',
    age: 71,
    gender: 'Male',
    phone: '+1 (415) 555-0167',
    email: 'robert.kim@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'B+',
    status: 'active',
    lastVisit: iso(addDays(today, -7)),
    address: '78 Cypress Lane, San Francisco, CA 94118',
    emergencyContact: {
      name: 'Susan Kim',
      relationship: 'Daughter',
      phone: '+1 (415) 555-0168',
    },
    medicalHistory: [
      {
        id: 'mh-6',
        date: iso(addDays(today, -7)),
        title: 'Atrial Fibrillation',
        description: 'New onset AFib, rate control initiated.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
      {
        id: 'mh-7',
        date: iso(addDays(today, -700)),
        title: 'Osteoarthritis',
        description: 'Bilateral knee osteoarthritis, conservative management.',
        doctor: 'Dr. Mark Lee',
        department: 'Orthopedics',
      },
    ],
    medications: [
      {
        id: 'med-6',
        name: 'Warfarin',
        dosage: '5mg',
        frequency: 'Once daily',
        startDate: iso(addDays(today, -7)),
        status: 'active',
      },
      {
        id: 'med-7',
        name: 'Diltiazem',
        dosage: '120mg',
        frequency: 'Once daily (extended release)',
        startDate: iso(addDays(today, -7)),
        status: 'active',
      },
      {
        id: 'med-8',
        name: 'Ibuprofen',
        dosage: '400mg',
        frequency: 'As needed for joint pain',
        startDate: iso(addDays(today, -700)),
        status: 'active',
      },
    ],
    allergies: ['Aspirin'],
    conditions: ['Atrial Fibrillation', 'Osteoarthritis', 'Hyperlipidemia'],
  },
  {
    id: 'p-4',
    name: 'Sophia Martinez',
    age: 27,
    gender: 'Female',
    phone: '+1 (415) 555-0125',
    email: 'sophia.m@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'AB+',
    status: 'new',
    lastVisit: iso(addDays(today, -1)),
    address: '924 Hill Street, San Francisco, CA 94114',
    emergencyContact: {
      name: 'Maria Martinez',
      relationship: 'Mother',
      phone: '+1 (415) 555-0126',
    },
    medicalHistory: [
      {
        id: 'mh-8',
        date: iso(addDays(today, -1)),
        title: 'Initial Consultation',
        description: 'New patient evaluation for recurrent chest tightness.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
    ],
    medications: [],
    allergies: [],
    conditions: ['Chest tightness (under investigation)'],
  },
  {
    id: 'p-5',
    name: 'David Thompson',
    age: 45,
    gender: 'Male',
    phone: '+1 (415) 555-0152',
    email: 'david.t@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'A-',
    status: 'active',
    lastVisit: iso(addDays(today, -21)),
    address: '137 Bayview Drive, San Francisco, CA 94124',
    emergencyContact: {
      name: 'Jennifer Thompson',
      relationship: 'Spouse',
      phone: '+1 (415) 555-0153',
    },
    medicalHistory: [
      {
        id: 'mh-9',
        date: iso(addDays(today, -21)),
        title: 'Exercise Stress Test',
        description: 'Normal exercise capacity, no ischemic changes.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
      {
        id: 'mh-10',
        date: iso(addDays(today, -120)),
        title: 'Hyperlipidemia',
        description: 'LDL 165, started on statin therapy.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
    ],
    medications: [
      {
        id: 'med-9',
        name: 'Rosuvastatin',
        dosage: '20mg',
        frequency: 'Once daily at bedtime',
        startDate: iso(addDays(today, -120)),
        status: 'active',
      },
    ],
    allergies: ['Sulfa drugs'],
    conditions: ['Hyperlipidemia', 'Family history of CAD'],
  },
  {
    id: 'p-6',
    name: 'Aisha Patel',
    age: 62,
    gender: 'Female',
    phone: '+1 (415) 555-0177',
    email: 'aisha.p@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'O+',
    status: 'follow-up',
    lastVisit: iso(addDays(today, -30)),
    address: '45 Laurel Way, San Francisco, CA 94109',
    emergencyContact: {
      name: 'Raj Patel',
      relationship: 'Son',
      phone: '+1 (415) 555-0178',
    },
    medicalHistory: [
      {
        id: 'mh-11',
        date: iso(addDays(today, -30)),
        title: 'Heart Failure Follow-up',
        description: 'Stable HFrEF, EF 35%, guideline-directed therapy continued.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
      {
        id: 'mh-12',
        date: iso(addDays(today, -500)),
        title: 'Heart Failure Diagnosis',
        description: 'HFrEF diagnosed, LVEF 30%, started GDMT.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
    ],
    medications: [
      {
        id: 'med-10',
        name: 'Carvedilol',
        dosage: '25mg',
        frequency: 'Twice daily',
        startDate: iso(addDays(today, -500)),
        status: 'active',
      },
      {
        id: 'med-11',
        name: 'Sacubitril/Valsartan',
        dosage: '49/51mg',
        frequency: 'Twice daily',
        startDate: iso(addDays(today, -300)),
        status: 'active',
      },
      {
        id: 'med-12',
        name: 'Furosemide',
        dosage: '40mg',
        frequency: 'Once daily',
        startDate: iso(addDays(today, -500)),
        status: 'active',
      },
    ],
    allergies: ['Codeine'],
    conditions: ['Heart Failure (HFrEF)', 'Chronic Kidney Disease Stage 2'],
  },
  {
    id: 'p-7',
    name: 'Michael O\'Brien',
    age: 39,
    gender: 'Male',
    phone: '+1 (415) 555-0134',
    email: 'michael.o@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/697509/pexels-photo-697509.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'A+',
    status: 'active',
    lastVisit: iso(addDays(today, -10)),
    address: '301 Valley Street, San Francisco, CA 94131',
    emergencyContact: {
      name: 'Kathleen O\'Brien',
      relationship: 'Spouse',
      phone: '+1 (415) 555-0135',
    },
    medicalHistory: [
      {
        id: 'mh-13',
        date: iso(addDays(today, -10)),
        title: 'Arrhythmia Consultation',
        description: 'Premature ventricular contractions, benign pattern.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
    ],
    medications: [],
    allergies: [],
    conditions: ['Benign PVCs'],
  },
  {
    id: 'p-8',
    name: 'Linda Walsh',
    age: 66,
    gender: 'Female',
    phone: '+1 (415) 555-0148',
    email: 'linda.w@email.com',
    avatarUrl:
      'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=256',
    bloodType: 'AB-',
    status: 'critical',
    lastVisit: iso(addDays(today, -2)),
    address: '88 Sea View Court, San Francisco, CA 94121',
    emergencyContact: {
      name: 'Thomas Walsh',
      relationship: 'Spouse',
      phone: '+1 (415) 555-0149',
    },
    medicalHistory: [
      {
        id: 'mh-14',
        date: iso(addDays(today, -2)),
        title: 'Unstable Angina',
        description: 'Admitted for NSTEMI, conservative management with GDMT.',
        doctor: 'Dr. Sarah Chen',
        department: 'Cardiology',
      },
    ],
    medications: [
      {
        id: 'med-13',
        name: 'Clopidogrel',
        dosage: '75mg',
        frequency: 'Once daily',
        startDate: iso(addDays(today, -2)),
        status: 'active',
      },
      {
        id: 'med-14',
        name: 'Ticagrelor',
        dosage: '90mg',
        frequency: 'Twice daily',
        startDate: iso(addDays(today, -2)),
        status: 'active',
      },
    ],
    allergies: ['Contrast dye'],
    conditions: ['NSTEMI', 'Coronary Artery Disease', 'Hypertension'],
  },
];

export const appointments: Appointment[] = [
  {
    id: 'a-1',
    patientId: 'p-1',
    patientName: 'James Morrison',
    patientAvatarUrl: patients[0].avatarUrl,
    time: '08:30',
    endTime: '09:00',
    date: iso(today),
    status: 'confirmed',
    priority: 'urgent',
    department: 'Cardiology',
    reason: 'Post-MI follow-up',
    durationMinutes: 30,
  },
  {
    id: 'a-2',
    patientId: 'p-4',
    patientName: 'Sophia Martinez',
    patientAvatarUrl: patients[3].avatarUrl,
    time: '09:15',
    endTime: '09:45',
    date: iso(today),
    status: 'pending',
    priority: 'medium',
    department: 'Cardiology',
    reason: 'Chest tightness evaluation',
    durationMinutes: 30,
  },
  {
    id: 'a-3',
    patientId: 'p-3',
    patientName: 'Robert Kim',
    patientAvatarUrl: patients[2].avatarUrl,
    time: '10:00',
    endTime: '10:30',
    date: iso(today),
    status: 'confirmed',
    priority: 'high',
    department: 'Cardiology',
    reason: 'AFib rate control review',
    durationMinutes: 30,
  },
  {
    id: 'a-4',
    patientId: 'p-5',
    patientName: 'David Thompson',
    patientAvatarUrl: patients[4].avatarUrl,
    time: '11:00',
    endTime: '11:30',
    date: iso(today),
    status: 'completed',
    priority: 'low',
    department: 'Cardiology',
    reason: 'Lipid panel review',
    durationMinutes: 30,
  },
  {
    id: 'a-5',
    patientId: 'p-6',
    patientName: 'Aisha Patel',
    patientAvatarUrl: patients[5].avatarUrl,
    time: '13:00',
    endTime: '13:45',
    date: iso(today),
    status: 'confirmed',
    priority: 'high',
    department: 'Cardiology',
    reason: 'Heart failure management',
    durationMinutes: 45,
  },
  {
    id: 'a-6',
    patientId: 'p-8',
    patientName: 'Linda Walsh',
    patientAvatarUrl: patients[7].avatarUrl,
    time: '14:30',
    endTime: '15:15',
    date: iso(today),
    status: 'pending',
    priority: 'urgent',
    department: 'Cardiology',
    reason: 'Post-NSTEMI assessment',
    durationMinutes: 45,
  },
  {
    id: 'a-7',
    patientId: 'p-2',
    patientName: 'Emily Rodriguez',
    patientAvatarUrl: patients[1].avatarUrl,
    time: '15:30',
    endTime: '16:00',
    date: iso(today),
    status: 'confirmed',
    priority: 'medium',
    department: 'Cardiology',
    reason: 'Holter monitor results',
    durationMinutes: 30,
  },
  {
    id: 'a-8',
    patientId: 'p-7',
    patientName: "Michael O'Brien",
    patientAvatarUrl: patients[6].avatarUrl,
    time: '16:15',
    endTime: '16:45',
    date: iso(today),
    status: 'cancelled',
    priority: 'low',
    department: 'Cardiology',
    reason: 'PVC follow-up',
    durationMinutes: 30,
  },
  // Tomorrow
  {
    id: 'a-9',
    patientId: 'p-1',
    patientName: 'James Morrison',
    patientAvatarUrl: patients[0].avatarUrl,
    time: '09:00',
    endTime: '09:30',
    date: iso(addDays(today, 1)),
    status: 'confirmed',
    priority: 'high',
    department: 'Cardiology',
    reason: 'Medication titration',
    durationMinutes: 30,
  },
  {
    id: 'a-10',
    patientId: 'p-3',
    patientName: 'Robert Kim',
    patientAvatarUrl: patients[2].avatarUrl,
    time: '11:00',
    endTime: '11:30',
    date: iso(addDays(today, 1)),
    status: 'pending',
    priority: 'medium',
    department: 'Cardiology',
    reason: 'INR check',
    durationMinutes: 30,
  },
  // Day after tomorrow
  {
    id: 'a-11',
    patientId: 'p-6',
    patientName: 'Aisha Patel',
    patientAvatarUrl: patients[5].avatarUrl,
    time: '10:00',
    endTime: '10:45',
    date: iso(addDays(today, 2)),
    status: 'confirmed',
    priority: 'high',
    department: 'Cardiology',
    reason: 'Echo review',
    durationMinutes: 45,
  },
  {
    id: 'a-12',
    patientId: 'p-8',
    patientName: 'Linda Walsh',
    patientAvatarUrl: patients[7].avatarUrl,
    time: '14:00',
    endTime: '14:30',
    date: iso(addDays(today, 2)),
    status: 'confirmed',
    priority: 'urgent',
    department: 'Cardiology',
    reason: 'Dual antiplatelet review',
    durationMinutes: 30,
  },
  // In 5 days
  {
    id: 'a-13',
    patientId: 'p-2',
    patientName: 'Emily Rodriguez',
    patientAvatarUrl: patients[1].avatarUrl,
    time: '09:30',
    endTime: '10:00',
    date: iso(addDays(today, 5)),
    status: 'confirmed',
    priority: 'low',
    department: 'Cardiology',
    reason: 'Routine follow-up',
    durationMinutes: 30,
  },
  {
    id: 'a-14',
    patientId: 'p-5',
    patientName: 'David Thompson',
    patientAvatarUrl: patients[4].avatarUrl,
    time: '13:00',
    endTime: '13:30',
    date: iso(addDays(today, 5)),
    status: 'pending',
    priority: 'medium',
    department: 'Cardiology',
    reason: 'Statin efficacy review',
    durationMinutes: 30,
  },
  // In 7 days
  {
    id: 'a-15',
    patientId: 'p-4',
    patientName: 'Sophia Martinez',
    patientAvatarUrl: patients[3].avatarUrl,
    time: '10:30',
    endTime: '11:00',
    date: iso(addDays(today, 7)),
    status: 'confirmed',
    priority: 'medium',
    department: 'Cardiology',
    reason: 'Follow-up after workup',
    durationMinutes: 30,
  },
  // In 10 days
  {
    id: 'a-16',
    patientId: 'p-7',
    patientName: "Michael O'Brien",
    patientAvatarUrl: patients[6].avatarUrl,
    time: '15:00',
    endTime: '15:30',
    date: iso(addDays(today, 10)),
    status: 'confirmed',
    priority: 'low',
    department: 'Cardiology',
    reason: 'Holter results discussion',
    durationMinutes: 30,
  },
];

export const conversations: Conversation[] = [
  {
    id: 'conv-1',
    patientId: 'p-4',
    patientName: 'Sophia Martinez',
    startedAt: isoDT(at(addDays(today, -1), 9, 30)),
    messageCount: 12,
    summaryId: 'sum-1',
  },
  {
    id: 'conv-2',
    patientId: 'p-8',
    patientName: 'Linda Walsh',
    startedAt: isoDT(at(addDays(today, -2), 14, 0)),
    messageCount: 18,
    summaryId: 'sum-2',
  },
  {
    id: 'conv-3',
    patientId: 'p-2',
    patientName: 'Emily Rodriguez',
    startedAt: isoDT(at(addDays(today, -14), 10, 15)),
    messageCount: 9,
    summaryId: 'sum-3',
  },
  {
    id: 'conv-4',
    patientId: 'p-6',
    patientName: 'Aisha Patel',
    startedAt: isoDT(at(addDays(today, -30), 11, 0)),
    messageCount: 15,
    summaryId: 'sum-4',
  },
];

export const chatMessages: ChatMessage[] = [
  // Conversation 1 — Sophia Martinez
  {
    id: 'm-1',
    conversationId: 'conv-1',
    sender: 'patient',
    content:
      "Hi, I've been having this chest tightness for about a week now. It comes and goes, usually when I'm resting.",
    timestamp: isoDT(at(addDays(today, -1), 9, 30)),
  },
  {
    id: 'm-2',
    conversationId: 'conv-1',
    sender: 'ai',
    content:
      "Thank you for sharing that, Sophia. I understand chest tightness can be concerning. Can you describe what the tightness feels like — is it a pressure, a sharp pain, or more of a burning sensation?",
    timestamp: isoDT(at(addDays(today, -1), 9, 31)),
  },
  {
    id: 'm-3',
    conversationId: 'conv-1',
    sender: 'patient',
    content:
      "It's like a pressure, right in the middle of my chest. Sometimes it spreads to my left arm.",
    timestamp: isoDT(at(addDays(today, -1), 9, 33)),
  },
  {
    id: 'm-4',
    conversationId: 'conv-1',
    sender: 'ai',
    content:
      "That's helpful to know. Pressure in the center of the chest that radiates to the left arm is something we want to evaluate carefully. A few more questions: Does it happen with physical activity or stress? How long does each episode last?",
    timestamp: isoDT(at(addDays(today, -1), 9, 34)),
  },
  {
    id: 'm-5',
    conversationId: 'conv-1',
    sender: 'patient',
    content:
      "It happens mostly when I'm stressed at work. Each episode lasts maybe 5-10 minutes. I've also been feeling short of breath.",
    timestamp: isoDT(at(addDays(today, -1), 9, 36)),
  },
  {
    id: 'm-6',
    conversationId: 'conv-1',
    sender: 'ai',
    content:
      "Thank you for those details. The combination of central chest pressure radiating to the left arm, triggered by stress, with associated shortness of breath is a pattern that warrants a thorough cardiac evaluation. I've flagged this for priority review by Dr. Chen. Do you have any family history of heart disease?",
    timestamp: isoDT(at(addDays(today, -1), 9, 37)),
  },
  {
    id: 'm-7',
    conversationId: 'conv-1',
    sender: 'patient',
    content:
      "My father had a heart attack at 55. I'm 27, so I thought I was too young for this.",
    timestamp: isoDT(at(addDays(today, -1), 9, 39)),
  },
  {
    id: 'm-8',
    conversationId: 'conv-1',
    sender: 'ai',
    content:
      "A family history of early heart disease is an important risk factor, even at your age. I've noted this in your pre-visit summary. Dr. Chen will review all of this information. In the meantime, if you experience chest pain that lasts more than 15 minutes, is severe, or comes with sweating or fainting, please go to the emergency room immediately.",
    timestamp: isoDT(at(addDays(today, -1), 9, 40)),
  },
  {
    id: 'm-9',
    conversationId: 'conv-1',
    sender: 'patient',
    content: "Okay, I understand. Thank you. I'm feeling a bit anxious about this.",
    timestamp: isoDT(at(addDays(today, -1), 9, 42)),
  },
  {
    id: 'm-10',
    conversationId: 'conv-1',
    sender: 'ai',
    content:
      "It's completely natural to feel anxious. The good news is you're taking the right step by getting it checked. Dr. Chen will be able to give you a clear assessment and plan. Your appointment is scheduled for today at 9:15 AM.",
    timestamp: isoDT(at(addDays(today, -1), 9, 43)),
  },
  {
    id: 'm-11',
    conversationId: 'conv-1',
    sender: 'patient',
    content: "That sounds good. I'll be there.",
    timestamp: isoDT(at(addDays(today, -1), 9, 44)),
  },
  {
    id: 'm-12',
    conversationId: 'conv-1',
    sender: 'ai',
    content:
      "Wonderful. I've prepared a summary of our conversation for Dr. Chen to review before your visit. Take care, and we'll see you soon.",
    timestamp: isoDT(at(addDays(today, -1), 9, 45)),
  },
  // Conversation 2 — Linda Walsh
  {
    id: 'm-13',
    conversationId: 'conv-2',
    sender: 'patient',
    content:
      "I woke up at 3 AM with terrible chest pressure. I was sweating and felt nauseous. My husband called 911.",
    timestamp: isoDT(at(addDays(today, -2), 14, 0)),
  },
  {
    id: 'm-14',
    conversationId: 'conv-2',
    sender: 'ai',
    content:
      "Mrs. Walsh, I'm very sorry you experienced that. It sounds like you had a serious episode. Were you admitted to the hospital?",
    timestamp: isoDT(at(addDays(today, -2), 14, 2)),
  },
  {
    id: 'm-15',
    conversationId: 'conv-2',
    sender: 'patient',
    content:
      "Yes, they said I had a type of heart attack called NSTEMI. They put me on several new medications.",
    timestamp: isoDT(at(addDays(today, -2), 14, 4)),
  },
  {
    id: 'm-16',
    conversationId: 'conv-2',
    sender: 'ai',
    content:
      "I see. An NSTEMI is a non-ST elevation myocardial infarction — a serious event that requires careful follow-up. Can you tell me the names of the new medications they started you on?",
    timestamp: isoDT(at(addDays(today, -2), 14, 5)),
  },
  {
    id: 'm-17',
    conversationId: 'conv-2',
    sender: 'patient',
    content:
      "I think they're called clopidogrel and ticagrelor. Plus something for my blood pressure that I was already taking.",
    timestamp: isoDT(at(addDays(today, -2), 14, 7)),
  },
  {
    id: 'm-18',
    conversationId: 'conv-2',
    sender: 'ai',
    content:
      "Thank you. Those are dual antiplatelet medications, which are standard after an NSTEMI. I've recorded these for Dr. Chen's review. Are you experiencing any chest discomfort now, or any shortness of breath, dizziness, or unusual bleeding?",
    timestamp: isoDT(at(addDays(today, -2), 14, 8)),
  },
  {
    id: 'm-19',
    conversationId: 'conv-2',
    sender: 'patient',
    content:
      "No chest pain now, but I feel very tired and a little short of breath when I walk. I'm also bruising more easily.",
    timestamp: isoDT(at(addDays(today, -2), 14, 10)),
  },
  {
    id: 'm-20',
    conversationId: 'conv-2',
    sender: 'ai',
    content:
      "Fatigue and mild shortness of breath with exertion can be expected in the first days after a heart attack. The easy bruising is a known effect of your new medications. However, the shortness of breath is something Dr. Chen will want to evaluate directly. I've flagged this as a high-priority item. Do you have any allergies to medications?",
    timestamp: isoDT(at(addDays(today, -2), 14, 11)),
  },
  {
    id: 'm-21',
    conversationId: 'conv-2',
    sender: 'patient',
    content: "Yes, I had a bad reaction to contrast dye during a CT scan once.",
    timestamp: isoDT(at(addDays(today, -2), 14, 13)),
  },
  {
    id: 'm-22',
    conversationId: 'conv-2',
    sender: 'ai',
    content:
      "That's important — I've noted a contrast dye allergy in your record. This is relevant if any imaging with contrast is considered. Dr. Chen will review your full summary, including the NSTEMI, your new dual antiplatelet therapy, the shortness of breath, and your contrast allergy. Your appointment is today at 2:30 PM. Please bring all your medication bottles if you can.",
    timestamp: isoDT(at(addDays(today, -2), 14, 14)),
  },
];

export const aiSummaries: AiSummary[] = [
  {
    id: 'sum-1',
    patientId: 'p-4',
    patientName: 'Sophia Martinez',
    appointmentId: 'a-2',
    generatedAt: isoDT(at(addDays(today, -1), 9, 46)),
    chiefComplaint:
      'Recurrent central chest pressure radiating to the left arm, occurring over the past week, primarily stress-induced.',
    symptomsSummary: [
      'Central chest pressure lasting 5-10 minutes per episode',
      'Radiation to the left arm',
      'Associated shortness of breath',
      'Triggered by stress, occurs at rest',
      'Patient reports anxiety about symptoms',
    ],
    medicalHistorySummary:
      '27-year-old female with no significant prior medical history. Father had an MI at age 55, indicating a family history of premature coronary artery disease. No current medications. No known allergies.',
    riskFlags: [
      'Family history of premature CAD (father, age 55)',
      'Symptom pattern concerning for angina despite young age',
      'Radiation to left arm — cardiac origin likely',
    ],
    missingInformation: [
      'Smoking status not reported',
      'Blood pressure and lipid panel not on file',
      'BMI and physical activity level unknown',
      'No prior ECG or cardiac workup on record',
    ],
    suggestedFollowUpQuestions: [
      'Have you noticed any pattern in when the episodes occur beyond stress?',
      'Do you smoke or use any nicotine products?',
      'Have you ever had your cholesterol checked?',
      'Is there any family history of clotting disorders?',
    ],
    conversationId: 'conv-1',
    confidence: 88,
  },
  {
    id: 'sum-2',
    patientId: 'p-8',
    patientName: 'Linda Walsh',
    appointmentId: 'a-6',
    generatedAt: isoDT(at(addDays(today, -2), 14, 16)),
    chiefComplaint:
      'Post-NSTEMI follow-up. Patient discharged 2 days ago on dual antiplatelet therapy with residual exertional dyspnea.',
    symptomsSummary: [
      'No current chest pain at rest',
      'Exertional shortness of breath (new since event)',
      'Generalized fatigue',
      'Easy bruising (attributed to new medications)',
    ],
    medicalHistorySummary:
      '66-year-old female, recent NSTEMI managed conservatively. Now on clopidogrel 75mg and ticagrelor 90mg BID. Known hypertension. Allergy to contrast dye. No prior cardiac history before this event.',
    riskFlags: [
      'Recent NSTEMI (2 days ago) — high-risk window',
      'New exertional dyspnea may indicate ongoing ischemia or heart failure',
      'Dual antiplatelet therapy — bleeding risk assessment needed',
      'Contrast dye allergy limits some imaging options',
    ],
    missingInformation: [
      'Discharge echocardiogram results not yet uploaded',
      'Ejection fraction not documented',
      'Renal function post-event unknown',
      'Complete medication reconciliation needed (patient unsure of all meds)',
    ],
    suggestedFollowUpQuestions: [
      'Can you describe exactly what level of activity causes the shortness of breath?',
      'Have you had any episodes of chest pain since discharge?',
      'Are you experiencing any palpitations or dizziness?',
      'Do you have your discharge paperwork and all medication bottles with you?',
    ],
    conversationId: 'conv-2',
    confidence: 92,
  },
  {
    id: 'sum-3',
    patientId: 'p-2',
    patientName: 'Emily Rodriguez',
    appointmentId: 'a-7',
    generatedAt: isoDT(at(addDays(today, -14), 10, 20)),
    chiefComplaint:
      'Episodic palpitations over the past 3 months, currently wearing a Holter monitor for evaluation.',
    symptomsSummary: [
      'Palpitations described as "fluttering" in the chest',
      'Episodes last seconds to a few minutes',
      'No associated chest pain or syncope',
      'Occasional mild lightheadedness',
      'Symptoms correlate with caffeine intake and stress',
    ],
    medicalHistorySummary:
      '34-year-old female with history of migraine with aura and anxiety. On sumatriptan PRN. Latex allergy. No prior cardiac history. Holter monitor placed 14 days ago — results pending review.',
    riskFlags: [
      'Palpitations with lightheadedness warrant rhythm documentation',
      'Anxiety may be a contributor but cardiac cause not excluded',
    ],
    missingInformation: [
      'Holter monitor report not yet reviewed in this conversation',
      'Thyroid function not assessed',
      'Caffeine and alcohol intake quantification needed',
    ],
    suggestedFollowUpQuestions: [
      'How many episodes did the Holter monitor capture?',
      'Have you noticed any correlation with your menstrual cycle?',
      'What is your typical daily caffeine intake?',
    ],
    conversationId: 'conv-3',
    confidence: 85,
  },
  {
    id: 'sum-4',
    patientId: 'p-6',
    patientName: 'Aisha Patel',
    appointmentId: 'a-5',
    generatedAt: isoDT(at(addDays(today, -30), 11, 10)),
    chiefComplaint:
      'Routine heart failure follow-up. Patient reports stable symptoms on current GDMT.',
    symptomsSummary: [
      'No orthopnea or paroxysmal nocturnal dyspnea',
      'Mild exertional fatigue — unchanged from last visit',
      'No lower extremity edema',
      'Home weight monitoring stable',
      'No recent hospitalizations',
    ],
    medicalHistorySummary:
      '62-year-old female with HFrEF (LVEF 35%), CKD Stage 2. On maximally tolerated GDMT: carvedilol, sacubitril/valsartan, furosemide. Codeine allergy. Last echo 30 days ago confirmed stable EF.',
    riskFlags: [
      'CKD Stage 2 — requires monitoring with medication adjustments',
      'Codeine allergy noted — avoid opioids',
    ],
    missingInformation: [
      'Recent BMP results not uploaded since last visit',
      'Patient self-reported weight trends need confirmation',
      'NT-proBNP trend not available',
    ],
    suggestedFollowUpQuestions: [
      'Have you missed any doses of your medications this month?',
      'How has your exercise tolerance been compared to last visit?',
      'Any swelling or weight changes noted at home?',
    ],
    conversationId: 'conv-4',
    confidence: 90,
  },
];

export const doctorNotes: DoctorNote[] = [
  {
    id: 'note-1',
    patientId: 'p-5',
    appointmentId: 'a-4',
    diagnosis: 'Hyperlipidemia — well controlled on rosuvastatin 20mg',
    clinicalNotes:
      'Patient reports good adherence to statin therapy. No muscle aches or weakness. Exercise stress test from 3 weeks ago was negative for ischemia. LDL down from 165 to 92. Patient is motivated and following lifestyle recommendations.',
    treatmentPlan:
      'Continue rosuvastatin 20mg daily. Repeat lipid panel in 6 months. Reinforce Mediterranean diet and 150 min/week of moderate exercise. No further cardiac workup indicated at this time.',
    prescription: 'Rosuvastatin 20mg, take one tablet by mouth at bedtime. #90, 3 refills.',
    followUpDate: iso(addDays(today, 180)),
    createdAt: isoDT(at(today, 11, 15)),
    updatedAt: isoDT(at(today, 11, 20)),
  },
];

export const notifications: AppNotification[] = [
  {
    id: 'n-1',
    type: 'appointment_request',
    title: 'New appointment request',
    description: 'Sophia Martinez requested a consultation for chest tightness.',
    timestamp: isoDT(at(addDays(today, -1), 16, 30)),
    read: false,
    patientId: 'p-4',
  },
  {
    id: 'n-2',
    type: 'emergency',
    title: 'Emergency case flagged',
    description: 'Linda Walsh admitted for NSTEMI — requires urgent follow-up.',
    timestamp: isoDT(at(addDays(today, -2), 3, 45)),
    read: false,
    patientId: 'p-8',
  },
  {
    id: 'n-3',
    type: 'summary_ready',
    title: 'AI summary ready for review',
    description: 'Pre-visit AI summary for Sophia Martinez is ready.',
    timestamp: isoDT(at(addDays(today, -1), 9, 46)),
    read: false,
    patientId: 'p-4',
  },
  {
    id: 'n-4',
    type: 'cancellation',
    title: 'Appointment cancelled',
    description: "Michael O'Brien cancelled today's 4:15 PM appointment.",
    timestamp: isoDT(at(today, 7, 15)),
    read: false,
    patientId: 'p-7',
  },
  {
    id: 'n-5',
    type: 'appointment_request',
    title: 'New appointment request',
    description: 'David Thompson requested a statin efficacy review.',
    timestamp: isoDT(at(addDays(today, -1), 14, 0)),
    read: true,
    patientId: 'p-5',
  },
  {
    id: 'n-6',
    type: 'system',
    title: 'Lab results available',
    description: 'James Morrison\'s lipid panel and BMP are now available.',
    timestamp: isoDT(at(today, 6, 30)),
    read: true,
    patientId: 'p-1',
  },
  {
    id: 'n-7',
    type: 'summary_ready',
    title: 'AI summary ready for review',
    description: 'Pre-visit AI summary for Linda Walsh is ready.',
    timestamp: isoDT(at(addDays(today, -2), 14, 16)),
    read: true,
    patientId: 'p-8',
  },
];

// Analytics chart data
export const weeklyAppointmentTrend = [
  { day: 'Mon', appointments: 8, completed: 6 },
  { day: 'Tue', appointments: 10, completed: 9 },
  { day: 'Wed', appointments: 7, completed: 7 },
  { day: 'Thu', appointments: 12, completed: 10 },
  { day: 'Fri', appointments: 9, completed: 8 },
  { day: 'Sat', appointments: 4, completed: 4 },
  { day: 'Sun', appointments: 0, completed: 0 },
];

export const monthlyConsultationTrend = [
  { month: 'Jan', visits: 142, avg: 22 },
  { month: 'Feb', visits: 158, avg: 24 },
  { month: 'Mar', visits: 171, avg: 25 },
  { month: 'Apr', visits: 165, avg: 23 },
  { month: 'May', visits: 189, avg: 26 },
  { month: 'Jun', visits: 178, avg: 25 },
  { month: 'Jul', visits: 195, avg: 27 },
];

export const departmentDistribution = [
  { name: 'Cardiology', value: 48, color: 'hsl(var(--chart-1))' },
  { name: 'Neurology', value: 18, color: 'hsl(var(--chart-2))' },
  { name: 'General Med', value: 14, color: 'hsl(var(--chart-3))' },
  { name: 'Orthopedics', value: 10, color: 'hsl(var(--chart-4))' },
  { name: 'Other', value: 10, color: 'hsl(var(--chart-5))' },
];

export const patientDemographics = [
  { range: '0-18', male: 4, female: 3 },
  { range: '19-35', male: 12, female: 15 },
  { range: '36-50', male: 22, female: 19 },
  { range: '51-65', male: 28, female: 25 },
  { range: '65+', male: 18, female: 21 },
];

export const doctorPerformance = [
  { metric: 'On-time', value: 94 },
  { metric: 'Patient sat.', value: 91 },
  { metric: 'Documentation', value: 88 },
  { metric: 'Follow-up rate', value: 96 },
  { metric: 'Avg. consult', value: 85 },
];

export const satisfactionTrend = [
  { month: 'Jan', score: 4.5 },
  { month: 'Feb', score: 4.6 },
  { month: 'Mar', score: 4.7 },
  { month: 'Apr', score: 4.5 },
  { month: 'May', score: 4.8 },
  { month: 'Jun', score: 4.7 },
  { month: 'Jul', score: 4.9 },
];
